#!/bin/bash

E_BADARGS=65
MYSQL=`which mysql`

Q1="CREATE DATABASE IF NOT EXISTS tutorial;"
Q2="GRANT ALL ON *.* TO 'jeffrey'@'localhost' IDENTIFIED BY 'mypass';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

/usr/sbin/mysqld &
sleep 5

$MYSQL -e "$SQL"

python manage.py syncd --noinputb
