#!/bin/bash

EXPECTED_ARGS=3
E_BADARGS=65
MYSQL=`which mysql`

Q1="CREATE DATABASE IF NOT EXISTS tutorial;"
Q2="GRANT ALL ON *.* TO 'jeffrey'@'localhost' IDENTIFIED BY 'mypass';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

if [ $# -ne $EXPECTED_ARGS ]
then
    echo "Usage: $0 dbname dbuser dbpass"
    exit $E_BADARGS
fi

$MYSQL -e "$SQL"

python manage.py syncdb
